default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: slamAPI_development

test:
  <<: *default
  database: slamAPI_test

production:
  <<: *default
  database: slamAPI_production
  username: slamAPI
  password: <%= ENV['SLAMAPI_DATABASE_PASSWORD'] %>
